[package]
name = "leetcode_solutions"
version = "0.1.0"
edition = "2021"
default-run = "rs_ans"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "rs_ans"
path = "src/rs_ans/main.rs"

[dependencies]
